name: Close All Issues

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  close_issues:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Use GitHub Script to fetch and close issues
      - name: Close All Issues
        uses: actions/github-script@v6
        with:
          script: |
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open", // Fetch all open issues
            });

            if (issues.length === 0) {
              core.info("No open issues found.");
            } else {
              for (const issue of issues) {
                if (!issue.pull_request) { // Ensure it's an issue, not a pull request
                  await github.rest.issues.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    state: "closed",
                  });
                  core.info(`Closed issue #${issue.number}: ${issue.title}`);
                }
              }
            }
